In [33]:
# Import necessary libraries
import sys
sys.path.append('../src')  # Add the src directory to the system path

from data_loader import DataLoader
from data_quality_check import DataQualityCheck
from data_clean_processing import DataCleanProcessing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score,f1_score
import xgboost as xgb

In [34]:
# Load the data
file_path = '../data/MachineLearningRating_v3.txt'
data_loader = DataLoader(file_path)
data = data_loader.load_data()

In [35]:
# Display basic info and head of the data
data_loader.basic_info()
data_loader.display_head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      854137 non-null   object
 9   AccountType               959866 non-null   object
 10  MaritalStatus             991839 non-null   object
 11  Gender                    990562 non-null   object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   object
 22  Model                     999546 non-null   object
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   object
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   object
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  object
 31  TrackingDevice            1000098 non-null  object
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   object
 34  WrittenOff                358197 non-null   object
 35  Rebuilt                   358197 non-null   object
 36  Converted                 358197 non-null   object
 37  CrossBorder               698 non-null      object
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  object
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  object
 43  CoverCategory             1000098 non-null  object
 44  CoverType                 1000098 non-null  object
 45  CoverGroup                1000098 non-null  object
 46  Section                   1000098 non-null  object
 47  Product                   1000098 non-null  object
 48  StatutoryClass            1000098 non-null  object
 49  StatutoryRiskType         1000098 non-null  object
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(36)
memory usage: 390.1+ MB

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [36]:
# Checking Missing Values
data_quality = DataQualityCheck(file_path)
data = data_quality.load_data()
data_quality.basic_info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      854137 non-null   object
 9   AccountType               959866 non-null   object
 10  MaritalStatus             991839 non-null   object
 11  Gender                    990562 non-null   object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   object
 22  Model                     999546 non-null   object
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   object
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   object
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  object
 31  TrackingDevice            1000098 non-null  object
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   object
 34  WrittenOff                358197 non-null   object
 35  Rebuilt                   358197 non-null   object
 36  Converted                 358197 non-null   object
 37  CrossBorder               698 non-null      object
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  object
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  object
 43  CoverCategory             1000098 non-null  object
 44  CoverType                 1000098 non-null  object
 45  CoverGroup                1000098 non-null  object
 46  Section                   1000098 non-null  object
 47  Product                   1000098 non-null  object
 48  StatutoryClass            1000098 non-null  object
 49  StatutoryRiskType         1000098 non-null  object
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(36)
memory usage: 390.1+ MB
None
       UnderwrittenCoverID      PolicyID    PostalCode        mmcode  \
count         1.000098e+06  1.000098e+06  1.000098e+06  9.995460e+05
mean          1.048175e+05  7.956682e+03  3.020601e+03  5.487770e+07
std           6.329371e+04  5.290039e+03  2.649854e+03  1.360381e+07
min           1.000000e+00  1.400000e+01  1.000000e+00  4.041200e+06
25%           5.514300e+04  4.500000e+03  8.270000e+02  6.005692e+07
50%           9.408300e+04  7.071000e+03  2.000000e+03  6.005842e+07
75%           1.391900e+05  1.107700e+04  4.180000e+03  6.005842e+07
max           3.011750e+05  2.324600e+04  9.870000e+03  6.506535e+07

       RegistrationYear      Cylinders  cubiccapacity      kilowatts  \
count      1.000098e+06  999546.000000  999546.000000  999546.000000
mean       2.010225e+03       4.046642    2466.743258      97.207919
std        3.261391e+00       0.294020     442.800640      19.393256
min        1.987000e+03       0.000000       0.000000       0.000000
25%        2.008000e+03       4.000000    2237.000000      75.000000
50%        2.011000e+03       4.000000    2694.000000     111.000000
75%        2.013000e+03       4.000000    2694.000000     111.000000
max        2.015000e+03      10.000000   12880.000000     309.000000

       NumberOfDoors  CustomValueEstimate  NumberOfVehiclesInFleet  \
count  999546.000000         2.204560e+05                      0.0
mean        4.019250         2.255311e+05                      NaN
std         0.468314         5.645157e+05                      NaN
min         0.000000         2.000000e+04                      NaN
25%         4.000000         1.350000e+05                      NaN
50%         4.000000         2.200000e+05                      NaN
75%         4.000000         2.800000e+05                      NaN
max         6.000000         2.655000e+07                      NaN

         SumInsured  CalculatedPremiumPerTerm  TotalPremium   TotalClaims
count  1.000098e+06              1.000098e+06  1.000098e+06  1.000098e+06
mean   6.041727e+05              1.178757e+02  6.190550e+01  6.486119e+01
std    1.508332e+06              3.997017e+02  2.302845e+02  2.384075e+03
min    1.000000e-02              0.000000e+00 -7.825768e+02 -1.200241e+04
25%    5.000000e+03              3.224800e+00  0.000000e+00  0.000000e+00
50%    7.500000e+03              8.436900e+00  2.178333e+00  0.000000e+00
75%    2.500000e+05              9.000000e+01  2.192982e+01  0.000000e+00
max    1.263620e+07              7.442217e+04  6.528260e+04  3.930921e+05

In [37]:
# Clean the data
data_cleaner = DataCleanProcessing(data)
cleaned_data = data_cleaner.clean_missing_values()

# Verify no missing values
print("Verification of no missing values:", data_cleaner.verify_no_missing_values())

d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(mode)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)
d:\Insurance_Claims_Analysis\notebooks\../src\data_clean_processing.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned[column] = data_cleaned[column].fillna(median)

Verification of no missing values: True

In [38]:
# Display the first few rows of the cleaned data
cleaned_data.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [39]:
# Display the shape of the dataframe after cleaning, to check any drop column.
cleaned_data.shape

(1000098, 46)

In [40]:
# Display information about the dataframe
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 46 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      1000098 non-null  object
 9   AccountType               1000098 non-null  object
 10  MaritalStatus             1000098 non-null  object
 11  Gender                    1000098 non-null  object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    1000098 non-null  float64
 19  VehicleType               1000098 non-null  object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      1000098 non-null  object
 22  Model                     1000098 non-null  object
 23  Cylinders                 1000098 non-null  float64
 24  cubiccapacity             1000098 non-null  float64
 25  kilowatts                 1000098 non-null  float64
 26  bodytype                  1000098 non-null  object
 27  NumberOfDoors             1000098 non-null  float64
 28  VehicleIntroDate          1000098 non-null  object
 29  AlarmImmobiliser          1000098 non-null  object
 30  TrackingDevice            1000098 non-null  object
 31  CapitalOutstanding        1000098 non-null  object
 32  NewVehicle                1000098 non-null  object
 33  SumInsured                1000098 non-null  float64
 34  TermFrequency             1000098 non-null  object
 35  CalculatedPremiumPerTerm  1000098 non-null  float64
 36  ExcessSelected            1000098 non-null  object
 37  CoverCategory             1000098 non-null  object
 38  CoverType                 1000098 non-null  object
 39  CoverGroup                1000098 non-null  object
 40  Section                   1000098 non-null  object
 41  Product                   1000098 non-null  object
 42  StatutoryClass            1000098 non-null  object
 43  StatutoryRiskType         1000098 non-null  object
 44  TotalPremium              1000098 non-null  float64
 45  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(9), int64(4), object(32)
memory usage: 344.3+ MB

In [41]:
cleaned_data.dtypes

UnderwrittenCoverID           int64
PolicyID                      int64
TransactionMonth             object
IsVATRegistered                bool
Citizenship                  object
LegalType                    object
Title                        object
Language                     object
Bank                         object
AccountType                  object
MaritalStatus                object
Gender                       object
Country                      object
Province                     object
PostalCode                    int64
MainCrestaZone               object
SubCrestaZone                object
ItemType                     object
mmcode                      float64
VehicleType                  object
RegistrationYear              int64
make                         object
Model                        object
Cylinders                   float64
cubiccapacity               float64
kilowatts                   float64
bodytype                     object
NumberOfDoors               float64
VehicleIntroDate             object
AlarmImmobiliser             object
TrackingDevice               object
CapitalOutstanding           object
NewVehicle                   object
SumInsured                  float64
TermFrequency                object
CalculatedPremiumPerTerm    float64
ExcessSelected               object
CoverCategory                object
CoverType                    object
CoverGroup                   object
Section                      object
Product                      object
StatutoryClass               object
StatutoryRiskType            object
TotalPremium                float64
TotalClaims                 float64
dtype: object

In [42]:
cleaned_data.count()

UnderwrittenCoverID         1000098
PolicyID                    1000098
TransactionMonth            1000098
IsVATRegistered             1000098
Citizenship                 1000098
LegalType                   1000098
Title                       1000098
Language                    1000098
Bank                        1000098
AccountType                 1000098
MaritalStatus               1000098
Gender                      1000098
Country                     1000098
Province                    1000098
PostalCode                  1000098
MainCrestaZone              1000098
SubCrestaZone               1000098
ItemType                    1000098
mmcode                      1000098
VehicleType                 1000098
RegistrationYear            1000098
make                        1000098
Model                       1000098
Cylinders                   1000098
cubiccapacity               1000098
kilowatts                   1000098
bodytype                    1000098
NumberOfDoors               1000098
VehicleIntroDate            1000098
AlarmImmobiliser            1000098
TrackingDevice              1000098
CapitalOutstanding          1000098
NewVehicle                  1000098
SumInsured                  1000098
TermFrequency               1000098
CalculatedPremiumPerTerm    1000098
ExcessSelected              1000098
CoverCategory               1000098
CoverType                   1000098
CoverGroup                  1000098
Section                     1000098
Product                     1000098
StatutoryClass              1000098
StatutoryRiskType           1000098
TotalPremium                1000098
TotalClaims                 1000098
dtype: int64

In [43]:
cleaned_data.isnull().sum()

UnderwrittenCoverID         0
PolicyID                    0
TransactionMonth            0
IsVATRegistered             0
Citizenship                 0
LegalType                   0
Title                       0
Language                    0
Bank                        0
AccountType                 0
MaritalStatus               0
Gender                      0
Country                     0
Province                    0
PostalCode                  0
MainCrestaZone              0
SubCrestaZone               0
ItemType                    0
mmcode                      0
VehicleType                 0
RegistrationYear            0
make                        0
Model                       0
Cylinders                   0
cubiccapacity               0
kilowatts                   0
bodytype                    0
NumberOfDoors               0
VehicleIntroDate            0
AlarmImmobiliser            0
TrackingDevice              0
CapitalOutstanding          0
NewVehicle                  0
SumInsured                  0
TermFrequency               0
CalculatedPremiumPerTerm    0
ExcessSelected              0
CoverCategory               0
CoverType                   0
CoverGroup                  0
Section                     0
Product                     0
StatutoryClass              0
StatutoryRiskType           0
TotalPremium                0
TotalClaims                 0
dtype: int64

In [44]:
# Replace the original data with the cleaned data
data = cleaned_data

In [45]:
df = pd.DataFrame(data)

# Use the head() method to display the first few rows of the DataFrame
head_df = df.head()

# Print the head of the DataFrame
print("The head of the DataFrame is:\n", head_df)

The head of the DataFrame is:
    UnderwrittenCoverID  PolicyID     TransactionMonth  IsVATRegistered  \
0               145249     12827  2015-03-01 00:00:00             True
1               145249     12827  2015-05-01 00:00:00             True
2               145249     12827  2015-07-01 00:00:00             True
3               145255     12827  2015-05-01 00:00:00             True
4               145255     12827  2015-07-01 00:00:00             True

  Citizenship          LegalType Title Language                 Bank  \
0              Close Corporation    Mr  English  First National Bank
1              Close Corporation    Mr  English  First National Bank
2              Close Corporation    Mr  English  First National Bank
3              Close Corporation    Mr  English  First National Bank
4              Close Corporation    Mr  English  First National Bank

       AccountType  ...                    ExcessSelected CoverCategory  \
0  Current account  ...             Mobility - Windscreen    Windscreen
1  Current account  ...             Mobility - Windscreen    Windscreen
2  Current account  ...             Mobility - Windscreen    Windscreen
3  Current account  ...  Mobility - Metered Taxis - R2000    Own damage
4  Current account  ...  Mobility - Metered Taxis - R2000    Own damage

    CoverType            CoverGroup              Section  \
0  Windscreen  Comprehensive - Taxi  Motor Comprehensive
1  Windscreen  Comprehensive - Taxi  Motor Comprehensive
2  Windscreen  Comprehensive - Taxi  Motor Comprehensive
3  Own Damage  Comprehensive - Taxi  Motor Comprehensive
4  Own Damage  Comprehensive - Taxi  Motor Comprehensive

                           Product StatutoryClass StatutoryRiskType  \
0  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
1  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
2  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
3  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant
4  Mobility Metered Taxis: Monthly     Commercial     IFRS Constant

   TotalPremium TotalClaims
0     21.929825         0.0
1     21.929825         0.0
2      0.000000         0.0
3    512.848070         0.0
4      0.000000         0.0

[5 rows x 46 columns]

In [46]:
# Detect missing values
missing_values = df.isnull()
print("Missing values in the DataFrame:\n", missing_values)

# Count missing values in each column
missing_count = df.isnull().sum()
print("Count of missing values in each column:\n", missing_count)

Missing values in the DataFrame:
          UnderwrittenCoverID  PolicyID  TransactionMonth  IsVATRegistered  \
0                      False     False             False            False
1                      False     False             False            False
2                      False     False             False            False
3                      False     False             False            False
4                      False     False             False            False
...                      ...       ...               ...              ...
1000093                False     False             False            False
1000094                False     False             False            False
1000095                False     False             False            False
1000096                False     False             False            False
1000097                False     False             False            False

         Citizenship  LegalType  Title  Language   Bank  AccountType  ...  \
0              False      False  False     False  False        False  ...
1              False      False  False     False  False        False  ...
2              False      False  False     False  False        False  ...
3              False      False  False     False  False        False  ...
4              False      False  False     False  False        False  ...
...              ...        ...    ...       ...    ...          ...  ...
1000093        False      False  False     False  False        False  ...
1000094        False      False  False     False  False        False  ...
1000095        False      False  False     False  False        False  ...
1000096        False      False  False     False  False        False  ...
1000097        False      False  False     False  False        False  ...

         ExcessSelected  CoverCategory  CoverType  CoverGroup  Section  \
0                 False          False      False       False    False
1                 False          False      False       False    False
2                 False          False      False       False    False
3                 False          False      False       False    False
4                 False          False      False       False    False
...                 ...            ...        ...         ...      ...
1000093           False          False      False       False    False
1000094           False          False      False       False    False
1000095           False          False      False       False    False
1000096           False          False      False       False    False
1000097           False          False      False       False    False

         Product  StatutoryClass  StatutoryRiskType  TotalPremium  TotalClaims
0          False           False              False         False        False
1          False           False              False         False        False
2          False           False              False         False        False
3          False           False              False         False        False
4          False           False              False         False        False
...          ...             ...                ...           ...          ...
1000093    False           False              False         False        False
1000094    False           False              False         False        False
1000095    False           False              False         False        False
1000096    False           False              False         False        False
1000097    False           False              False         False        False

[1000098 rows x 46 columns]
Count of missing values in each column:
 UnderwrittenCoverID         0
PolicyID                    0
TransactionMonth            0
IsVATRegistered             0
Citizenship                 0
LegalType                   0
Title                       0
Language                    0
Bank                        0
AccountType                 0
MaritalStatus               0
Gender                      0
Country                     0
Province                    0
PostalCode                  0
MainCrestaZone              0
SubCrestaZone               0
ItemType                    0
mmcode                      0
VehicleType                 0
RegistrationYear            0
make                        0
Model                       0
Cylinders                   0
cubiccapacity               0
kilowatts                   0
bodytype                    0
NumberOfDoors               0
VehicleIntroDate            0
AlarmImmobiliser            0
TrackingDevice              0
CapitalOutstanding          0
NewVehicle                  0
SumInsured                  0
TermFrequency               0
CalculatedPremiumPerTerm    0
ExcessSelected              0
CoverCategory               0
CoverType                   0
CoverGroup                  0
Section                     0
Product                     0
StatutoryClass              0
StatutoryRiskType           0
TotalPremium                0
TotalClaims                 0
dtype: int64

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 46 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      1000098 non-null  object
 9   AccountType               1000098 non-null  object
 10  MaritalStatus             1000098 non-null  object
 11  Gender                    1000098 non-null  object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    1000098 non-null  float64
 19  VehicleType               1000098 non-null  object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      1000098 non-null  object
 22  Model                     1000098 non-null  object
 23  Cylinders                 1000098 non-null  float64
 24  cubiccapacity             1000098 non-null  float64
 25  kilowatts                 1000098 non-null  float64
 26  bodytype                  1000098 non-null  object
 27  NumberOfDoors             1000098 non-null  float64
 28  VehicleIntroDate          1000098 non-null  object
 29  AlarmImmobiliser          1000098 non-null  object
 30  TrackingDevice            1000098 non-null  object
 31  CapitalOutstanding        1000098 non-null  object
 32  NewVehicle                1000098 non-null  object
 33  SumInsured                1000098 non-null  float64
 34  TermFrequency             1000098 non-null  object
 35  CalculatedPremiumPerTerm  1000098 non-null  float64
 36  ExcessSelected            1000098 non-null  object
 37  CoverCategory             1000098 non-null  object
 38  CoverType                 1000098 non-null  object
 39  CoverGroup                1000098 non-null  object
 40  Section                   1000098 non-null  object
 41  Product                   1000098 non-null  object
 42  StatutoryClass            1000098 non-null  object
 43  StatutoryRiskType         1000098 non-null  object
 44  TotalPremium              1000098 non-null  float64
 45  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(9), int64(4), object(32)
memory usage: 344.3+ MB

In [48]:
# Basic statistical details
data.describe()

,UnderwrittenCoverID,PolicyID,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06
mean,1.048175e+05,7.956682e+03,3.020601e+03,5.488056e+07,2.010225e+03,4.046616e+00,2.466869e+03,9.721553e+01,4.019239e+00,6.041727e+05,1.178757e+02,6.190550e+01,6.486119e+01
std,6.329371e+04,5.290039e+03,2.649854e+03,1.360059e+07,3.261391e+00,2.939410e-01,4.427106e+02,1.939061e+01,4.681854e-01,1.508332e+06,3.997017e+02,2.302845e+02,2.384075e+03
min,1.000000e+00,1.400000e+01,1.000000e+00,4.041200e+06,1.987000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-02,0.000000e+00,-7.825768e+02,-1.200241e+04
25%,5.514300e+04,4.500000e+03,8.270000e+02,6.005692e+07,2.008000e+03,4.000000e+00,2.237000e+03,7.500000e+01,4.000000e+00,5.000000e+03,3.224800e+00,0.000000e+00,0.000000e+00
50%,9.408300e+04,7.071000e+03,2.000000e+03,6.005842e+07,2.011000e+03,4.000000e+00,2.694000e+03,1.110000e+02,4.000000e+00,7.500000e+03,8.436900e+00,2.178333e+00,0.000000e+00
75%,1.391900e+05,1.107700e+04,4.180000e+03,6.005842e+07,2.013000e+03,4.000000e+00,2.694000e+03,1.110000e+02,4.000000e+00,2.500000e+05,9.000000e+01,2.192982e+01,0.000000e+00
max,3.011750e+05,2.324600e+04,9.870000e+03,6.506535e+07,2.015000e+03,1.000000e+01,1.288000e+04,3.090000e+02,6.000000e+00,1.263620e+07,7.442217e+04,6.528260e+04,3.930921e+05

In [49]:
# Removing duplicate rows.
print('Duplicate Rows Count : ', data.duplicated().sum())
data=data.drop_duplicates(keep="first")

Duplicate Rows Count :  74

In [50]:
data.shape

(1000024, 46)

In [52]:
data.columns

Index(['UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
       'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
       'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
       'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
       'VehicleIntroDate', 'AlarmImmobiliser', 'TrackingDevice',
       'CapitalOutstanding', 'NewVehicle', 'SumInsured', 'TermFrequency',
       'CalculatedPremiumPerTerm', 'ExcessSelected', 'CoverCategory',
       'CoverType', 'CoverGroup', 'Section', 'Product', 'StatutoryClass',
       'StatutoryRiskType', 'TotalPremium', 'TotalClaims'],
      dtype='object')

### Editing Categorical Data

In [51]:
def encoder(method, dataframe, columns_label, columns_onehot):
    
    if method == 'labelEncoder':      
    
        df_lbl = dataframe.copy()
    
        for col in columns_label:
            label = LabelEncoder()
            label.fit(list(dataframe[col].values))
            df_lbl[col] = label.transform(df_lbl[col].values)
        
        return df_lbl
    
    elif method == 'oneHotEncoder':
        
        df_oh = dataframe.copy()

        df_oh= pd.get_dummies(data = df_oh, prefix = 'ohe', prefix_sep='_',
                       columns = columns_onehot,
                       drop_first =True,
                       dtype='int8')
        
        return df_oh